### ISSUE TITLE
Android-style slide over animation on wider menus jumps on pan gesture

### ISSUE THREAD

**Issue by OutRunner** [Douvi/SlideMenuDovi#5]
Hello,

I'm looking at using your slide menu in an upcoming project but I'm having a problem with the Android-style Slide Over animation. In your example project if I make the menu say 500 points wide and use the pan gesture to reveal it, it's jumping out too far. It's fine using the normal animation and using the on-screen button to reveal it, it's just the pan gesture. 

All I've added to RootViewController.swift is this:

`SliderMenuOptions.leftViewWidth = 500` 

Any thoughts on what I'm doing wrong?

Cheers!

**Comment by Douvi** [comment]
Hi OutRunner,

I guess you will need to set a bigger animation duration. The default value is 0.4s, so it's normal the menu is like jumping when it is opening or closing.

`SliderMenuOptions.animationDuration = X`

My Best

**Comment by OutRunner** [comment]
Hiya,

Thanks for the suggestion, I've had a go at increasing the `SliderMenuOptions.animationDuration` but it still seems to jump when first panning from the left to open the menu. I've recorded a gif to show you what I mean: 

[http://giphy.com/gifs/l46Cio10SZHYh7Asg](url)

It's that initial "jump" where a large portion of the menu pops onto the screen instead of smoothly following your finger as it drags right. It's fine when the menu is 242 points wide but any increase in the width causes part of the menu to pop onto the screen when first dragging. 

I think maybe it's something to do with `changedLeftTranslationGesture(frameTranslation: CGRect)` in AnimatorGestureSlideOver.swift, if I `print(frameTranslation)` the `origin.x` is -242 instead of -500 which I would have expected if the menu is 500 points wide. I could be wrong about that though! :)

Cheers!

**Comment by Douvi** [comment]
Hey OutRunner,

You are right, I did a little mistake at the method `applyLeftGestureTranslation`. I should use `leftViewWidth` instead the `rightViewWidth`.

A new release need to be send today with other fix. So I will add this one too.

Thanks
My Best.

**Comment by Douvi** [comment]
Added a fix this below 👍 

https://github.com/Douvi/SlideMenuDovi/pull/7/commits/427d6ee96a5e937a68cc3f9adadc91970fca59fe#diff-4af0838906021d7bf4c110655cc1f914L101

**Comment by OutRunner** [comment]
Thanks for fixing so quickly (and for making such an awesome slide menu that's really easy to integrate)! :)

Cheers!

**Comment by Douvi** [comment]
You're welcome, Cocoapod have been realise v1.0.0 

```
pod 'SlideMenuDovi', '1.0.0'
```

My Best
